version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'pdfParser'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'root'